### ISSUE TITLE
Develop a method for tracking our budget, especially in relation to incoming donations.

### ISSUE THREAD

**Issue by aubrel** [fabacab/the-lark#3]
We will need a method of tracking our incoming donations as well as our budget for paying contributors. Currently, contributors are paid $35 USD. We have our own bank account as well as accounts across digital payment platforms that we will need to track.

**Comment by fabacab** [comment]
This actually sounds like something that may be best left not integrated with the website at all, unless you want to accept donations in a manner that somehow credits individuals for their donation and tallies which person donated how much money, when, in what denominations, etc, in order to publish, publicize, or otherwise reward individual users for their *specific* contribution amounts. I personally think that's overkill.

Instead, consider the possibility that you simply need an accounting tool ([GNU Cash](https://gnucash.org/) comes to mind) to manage finances for this project, but that such accounting should be done independent of the website, since the two are kind of functioning at cross-purposes.

Since this is a *very* far-future issue and also one that will be tangential at best to the majority of the website, I am closing this issue and we can consider smaller chunks having to do with incoming donations attached to user accounts registered on the website when we need to.
